# Site settings
title: HollowayKeanHo
email: hollowaykeanho@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is HollowayKeanHo One Stop Portfolio website. It contains all related works and documentations for HollowayKeanHo.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: hollowaykeanho
github_username:  hollowaykeanho

# Build settings
markdown: kramdown
